### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by anpolimus** [drupal-ukraine/dranks#5]
During migration to D8 our goal is to fix architecture problems that we had previously.
1. Implement analytics_job as plugin and write next realisations for this plugin:

- [ ]   - country_scan_job - job that taking list of all users in a country and adding them to the queue;
- [ ]   - country_scan_job_item - job that is analysing profile one by one
- [ ]     - user scan : get commits - job that is scanning all commits for determined user
- [ ]     - user comments scan : get count of the comments for defined user
- [ ]     - user updates : scan for changes in user info (country, company, info)
- [ ]     - user comments statuses switch : scan for the issue status changing in a comment that is done by defined user.

2. Implement new cronjober component - service that is getting items in queue and try to resolve them one by one.

3. Implement master-slave status functionality.
By default, during git pull && vagrant up, we should configure instance as slave instance.
Slave instance is connecting to dranks.info main server and try to get queue items for himself.

We should have version verification and approve each new master in our network in order to avoid scan problems/bugs.

4. Implement Country statistics page.
Reimplement it from old versions - should be quite similar.

5.  CodeSprint analysator component.

- [ ]   - New CT that has list of atttenders (d.org users) and list of issues (d.org issues).
- [ ]   - Attenders and CS issues should scan each hour at the day of the sprint by jobs, described above.
- [ ]   - A dynamic report should be automatically updated after each jobs results.
- [ ]   - Display of the CS node could be displayed at the big screen of the CS room, showing who is making progress during CS and what issues are already fixed.
- [ ]   - When user added patch, changed status or added comment - system should show it at the newsevent in real time (once system get that info from any of job).

**Comment by podarok** [comment]
Use OpenY as a basic initial profile for the site

**Comment by podarok** [comment]
Next steps

- [x] 1 - init repo (OpenY + mapping entity + Syncer) @podarok
- [ ] 2 - Implement Country scanner (fetch from Drupal.org, write to Node (Country CT))
- [ ] 3 - Implement Commits scanner (fetch from Drupal.org, write to mapping entity (Commit bundle + fields), write to Node (User CT))
